name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]   # runs daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: jithnukaofficial
          template: classic
          filename: assets/metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
